### ISSUE TITLE
Worker runs but doesn't pull the pub data from ePubs

### ISSUE THREAD

**Issue by HadManySons** [willswire/api.afiexplorer.com#4]
```
Responding with all pubs
GET /.mf/scheduled/ 200 OK (7.27ms)
Responding with all pubs
GET / 200 OK (6.53ms)

hadmanysons@docker-host:~/api.afiexplorer.com$ miniflare worker.js -k STATIC_PUBS
[mf:inf] Worker reloaded! (4.29KiB)
[mf:inf] Listening on :8787
[mf:inf] - http://127.0.0.1:8787
[mf:inf] - http://192.168.2.253:8787
[mf:inf] - http://192.168.10.253:8787
[mf:inf] - http://172.17.0.1:8787
[mf:inf] - http://172.19.0.1:8787



Responding with all pubs
GET / 200 OK (32.98ms)
Responding with all pubs
GET / 200 OK (8.27ms)
Responding with all pubs
GET / 200 OK (5.65ms)
Responding with all pubs
GET / 200 OK (5.37ms)
Responding with all pubs
GET / 200 OK (7.06ms)
Responding with all pubs
GET / 200 OK (5.54ms)
Responding with all pubs
GET / 200 OK (6.92ms)
Responding with all pubs
GET / 200 OK (5.91ms)
```

But it doesn't return a JSON object. Perhaps I'm missing something?

**Comment by willswire** [comment]
Hey @HadManySons! Looks like you might need to generate some scheduled events (try a cron task) as described [here](https://miniflare.dev/core/scheduled). The worker will pull a different entry for each e-pubs endpoint depending on when the scheduled task occurs. I have mine set to run a cron task every minute.

I realize now that I need to update the repo with a package.json to include proper npm script definitions with these miniflare commands/flags. Thanks!

**Comment by HadManySons** [comment]
I did do that, at least based on whats on the README. That didn't work.

I ran this from the miniflare docs: curl "http://localhost:8787/cdn-cgi/mf/scheduled"

Which kind of worked, but then I get this: Error: MAJCOM_AFGSC_ALL data is invalid!

**Comment by HadManySons** [comment]
I also ran curl "http://localhost:8787/.mf/scheduled" from the same host, responded with "`[]`"

**Comment by willswire** [comment]
I’ll look into it some more on my end. The entire script will most likely change as I plan to roll out v2 of the API soon. This will include a better dev environment as well.
